"""Module for loading and running inference on summarization models."""
import logging
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM
from peft import PeftModel

from app.config import CUSTOM_MODEL_PATH
from app.custom_model_arch import EntityGuidedPureTransformer
from tokenizers import Tokenizer

from app.config import (
    BARTPHO_FFT_PATH, BARTPHO_LORA_PATH, QWEN_LORA_PATH,
    BARTPHO_BASE, QWEN_BASE,
    MAX_INPUT_LENGTH, MAX_OUTPUT_LENGTH, NUM_BEAMS,
)

logger = logging.getLogger(__name__)

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if torch.cuda.is_available() else torch.float32

_models = {}
_available_models = []


import re

def _clean_text(text: str) -> str:
    """Remove prompt remnants, special tokens, underscores, and fix punctuation spacing."""
    text = str(text)
    # Remove Qwen prompt remnants
    for marker in ['\n\nTóm tắt:', '\nTóm tắt:', 'Tóm tắt bài báo sau:']:
        idx = text.find(marker)
        if idx != -1:
            text = text[:idx].strip()
            
    # Handle special tokens
    # <unk> is often generated by BARTpho for '_' in word-segmented text
    text = text.replace('<unk>', ' ')
    for token in ['<s>', '</s>', '<pad>', '<|endoftext|>', '<|im_end|>', '<|im_start|>']:
        text = text.replace(token, '')
        
    # Replace underscores from word segmentation with spaces
    text = text.replace('_', ' ')
    
    # Fix punctuation spacing (e.g. " . " -> ". ", " , " -> ", ")
    text = re.sub(r'\s+([.,!?;:])', r'\1', text)
    text = re.sub(r'\(\s+', '(', text)
    text = re.sub(r'\s+\)', ')', text)
    
    # Clean up multiple spaces
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()


def load_models() -> list:
    """Load all available model checkpoints. Returns list of loaded model names."""
    global _models, _available_models
    _available_models = []

    # 1. BARTpho Full Fine-Tuning
    if BARTPHO_FFT_PATH.exists():
        try:
            logger.info(f"Loading BARTpho FFT from {BARTPHO_FFT_PATH}...")
            tokenizer = AutoTokenizer.from_pretrained(str(BARTPHO_FFT_PATH))
            model = AutoModelForSeq2SeqLM.from_pretrained(
                str(BARTPHO_FFT_PATH), torch_dtype=dtype
            ).to(device).eval()
            _models["bartpho_fft"] = {"model": model, "tokenizer": tokenizer, "type": "seq2seq"}
            _available_models.append("bartpho_fft")
            logger.info("BARTpho FFT loaded successfully.")
        except Exception as e:
            logger.warning(f"Failed to load BARTpho FFT: {e}")

    # 2. BARTpho LoRA
    if BARTPHO_LORA_PATH.exists():
        try:
            logger.info(f"Loading BARTpho LoRA from {BARTPHO_LORA_PATH}...")
            base_model = AutoModelForSeq2SeqLM.from_pretrained(BARTPHO_BASE, torch_dtype=dtype)
            model = PeftModel.from_pretrained(base_model, str(BARTPHO_LORA_PATH)).to(device).eval()
            tokenizer = AutoTokenizer.from_pretrained(str(BARTPHO_LORA_PATH))
            _models["bartpho_lora"] = {"model": model, "tokenizer": tokenizer, "type": "seq2seq"}
            _available_models.append("bartpho_lora")
            logger.info("BARTpho LoRA loaded successfully.")
        except Exception as e:
            logger.warning(f"Failed to load BARTpho LoRA: {e}")

    # 3. Qwen2.5 LoRA
    if QWEN_LORA_PATH.exists():
        try:
            logger.info(f"Loading Qwen2.5 LoRA from {QWEN_LORA_PATH}...")
            base_model = AutoModelForCausalLM.from_pretrained(
                QWEN_BASE, torch_dtype=dtype, trust_remote_code=True
            )
            model = PeftModel.from_pretrained(base_model, str(QWEN_LORA_PATH)).to(device).eval()
            tokenizer = AutoTokenizer.from_pretrained(QWEN_BASE, trust_remote_code=True)
            if tokenizer.pad_token is None:
                tokenizer.pad_token = tokenizer.eos_token
            _models["qwen_lora"] = {"model": model, "tokenizer": tokenizer, "type": "causal"}
            _available_models.append("qwen_lora")
            logger.info("Qwen2.5 LoRA loaded successfully.")
        except Exception as e:
            logger.warning(f"Failed to load Qwen2.5 LoRA: {e}")


    # 4. Custom Transformer (EntityGuidedPureTransformer)
    if CUSTOM_MODEL_PATH.exists():
        try:
            logger.info(f"Loading Custom Transformer from {CUSTOM_MODEL_PATH}...")
            # Load tokenizer
            tokenizer_path = CUSTOM_MODEL_PATH / "train_summarization_tokenizer.json"
            custom_tokenizer = Tokenizer.from_file(str(tokenizer_path))
            
            # Load model
            model = EntityGuidedPureTransformer(d_model=512, d_ff=1365, d_ff_new=1365, h=8, N=11)
            ckpt_path = CUSTOM_MODEL_PATH / "best_checkpoint.pt"
            ckpt = torch.load(str(ckpt_path), map_location=device)
            state_dict = ckpt['model_state_dict']
            if list(state_dict.keys())[0].startswith('module.'):
                state_dict = {k.replace('module.', ''): v for k, v in state_dict.items()}
            model.load_state_dict(state_dict)
            model = model.to(device).eval()
            
            _models["custom_transformer"] = {"model": model, "tokenizer": custom_tokenizer, "type": "custom"}
            _available_models.append("custom_transformer")
            logger.info("Custom Transformer loaded successfully.")
        except Exception as e:
            logger.warning(f"Failed to load Custom Transformer: {e}")

    if not _available_models:
        logger.warning("No model checkpoints found. Only pre-computed sample browser will work.")

    return _available_models


def get_available_models() -> list:
    """Return list of successfully loaded model names."""
    return _available_models


def generate_summary(model_name: str, text: str) -> str:
    """Generate summary from a specific model."""
    if model_name not in _models:
        return f"[Model '{model_name}' not available]"

    entry = _models[model_name]
    model = entry["model"]
    tokenizer = entry["tokenizer"]
    model_type = entry["type"]

    with torch.no_grad():
        if model_type == "seq2seq":
            inputs = tokenizer(
                text, max_length=MAX_INPUT_LENGTH,
                truncation=True, return_tensors="pt"
            ).to(device)
            outputs = model.generate(
                **inputs, max_length=MAX_OUTPUT_LENGTH,
                num_beams=NUM_BEAMS, early_stopping=True,
                repetition_penalty=1.2, no_repeat_ngram_size=3,
            )
            # Set skip_special_tokens=False so <unk> (representing underscores) is preserved
            summary = tokenizer.decode(outputs[0], skip_special_tokens=False)
            summary = _clean_text(summary)

        elif model_type == "causal":
            prompt = f"Tóm tắt bài báo sau:\n{text}\n\nTóm tắt:\n"
            inputs = tokenizer(
                prompt, max_length=MAX_INPUT_LENGTH,
                truncation=True, return_tensors="pt"
            ).to(device)
            prompt_length = inputs["input_ids"].shape[1]
            outputs = model.generate(
                **inputs, max_new_tokens=MAX_OUTPUT_LENGTH,
                num_beams=NUM_BEAMS, early_stopping=True,
                repetition_penalty=1.2, no_repeat_ngram_size=3,
                pad_token_id=tokenizer.eos_token_id,
            )
            summary_ids = outputs[0][prompt_length:]
            summary = tokenizer.decode(summary_ids, skip_special_tokens=True)
            summary = _clean_text(summary)

        elif model_type == "custom":
            # Custom Tokenizer logic
            enc = tokenizer.encode(text)
            input_ids = enc.ids[:MAX_INPUT_LENGTH]
            # Custom tokenizer has <BOS> (2), <EOS> (3), <PAD> (0)
            src_token = torch.tensor([input_ids], dtype=torch.long, device=device)
            src_mask = (src_token != 0).unsqueeze(1).unsqueeze(2) # [1, 1, 1, seq_len]
            
            summary_ids = model.generate_summary(
                src_token, src_mask, 
                bos_idx=2, eos_idx=3, pad_idx=0, 
                max_len=MAX_OUTPUT_LENGTH, strategy='greedy_with_penalty', penalty_tensor=torch.ones(1, tokenizer.get_vocab_size(), device=device) * 1.5, base_penalty=5.0
            )
            # Decoder returns [batch, seq_len]
            summary_ids = summary_ids[0].tolist()
            # Stop at EOS if present
            if 3 in summary_ids:
                summary_ids = summary_ids[:summary_ids.index(3)]
            # Remove BOS
            if len(summary_ids) > 0 and summary_ids[0] == 2:
                summary_ids = summary_ids[1:]
            
            summary = tokenizer.decode(summary_ids)
            summary = _clean_text(summary)

        else:
            return "[Unknown model type]"

    return summary


import concurrent.futures

def generate_all(text: str) -> dict:
    """Run inference on all loaded models concurrently."""
    results = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(_available_models)) as executor:
        future_to_name = {
            executor.submit(generate_summary, name, text): name 
            for name in _available_models
        }
        for future in concurrent.futures.as_completed(future_to_name):
            name = future_to_name[future]
            try:
                results[name] = future.result()
            except Exception as exc:
                logger.error(f"{name} generated an exception: {exc}")
                results[name] = f"[Error: {exc}]"
    return results
