import json

with open('09_Qwen_GTF_Penalty.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        source_text = ''.join(cell['source'])
        if 'class GTFPenaltyLogitsProcessor(LogitsProcessor):' in source_text:
            new_source = [
                'import torch\n',
                'import math\n',
                'import pandas as pd\n',
                'from tqdm.auto import tqdm\n',
                'from transformers import AutoTokenizer, AutoModelForCausalLM, LogitsProcessor, LogitsProcessorList\n',
                'from peft import PeftModel\n\n',
                'class GTFPenaltyLogitsProcessor(LogitsProcessor):\n',
                '    def __init__(self, vocab_frequencies: dict, prompt_length: int, alpha: float = 1.0, base_penalty: float = 0.6):\n',
                '        self.vocab_frequencies = vocab_frequencies\n',
                '        self.prompt_length = prompt_length\n',
                '        self.alpha = alpha\n',
                '        self.base_penalty = base_penalty\n',
                '        \n',
                '        if vocab_frequencies:\n',
                '            self.c_max = max(vocab_frequencies.values())\n',
                '        else:\n',
                '            self.c_max = 1\n',
                '            \n',
                '        self.log_c_max = math.log(self.c_max) if self.c_max > 1 else 1.0\n',
                '\n',
                '        max_token_id = max(vocab_frequencies.keys()) if vocab_frequencies else 0\n',
                '        self.P_v = torch.zeros(max_token_id + 1)\n',
                '        \n',
                '        for token_id, count in vocab_frequencies.items():\n',
                '            if count > 0:\n',
                '                p_v = self.alpha * (1.0 - (math.log(count) / self.log_c_max))\n',
                '            else:\n',
                '                p_v = self.alpha\n',
                '            self.P_v[token_id] = p_v\n',
                '            \n',
                '        self.P_v_device = None\n',
                '\n',
                '    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor) -> torch.FloatTensor:\n',
                '        batch_size, vocab_size = scores.shape\n',
                '        \n',
                '        if self.P_v_device is None or self.P_v_device.device != scores.device:\n',
                '            if vocab_size > len(self.P_v):\n',
                '                extended_P_v = torch.full((vocab_size,), self.alpha)\n',
                '                extended_P_v[:len(self.P_v)] = self.P_v\n',
                '                self.P_v = extended_P_v\n',
                '            self.P_v_device = self.P_v.to(scores.device)\n',
                '\n',
                '        for i in range(batch_size):\n',
                '            # CHỈ ĐẾM CÁC TOKEN TRONG PHẦN GENERATED SUMMARY (BỎ QUA PROMPT)\n',
                '            seq = input_ids[i][self.prompt_length:]\n',
                '            unique_tokens, counts = torch.unique(seq, return_counts=True)\n',
                '            \n',
                '            valid_mask = unique_tokens < vocab_size\n',
                '            unique_tokens = unique_tokens[valid_mask]\n',
                '            counts = counts[valid_mask].float()\n',
                '            \n',
                '            if len(unique_tokens) > 0:\n',
                '                penalty = (self.P_v_device[unique_tokens] * counts) + self.base_penalty\n',
                '                scores[i, unique_tokens] -= penalty\n',
                '\n',
                '        return scores\n'
            ]
            cell['source'] = new_source
        
        elif 'def generate_summary' in source_text and 'process_qwen' in source_text:
            new_source = [
                'def process_qwen(text):\n',
                '    text = str(text)\n',
                '    idx = text.find(\'\\n\\nTóm tắt:\')\n',
                '    if idx == -1: idx = text.find(\'\\nTóm tắt:\')\n',
                '    if idx == -1: idx = text.find(\'Tóm tắt bài báo sau:\')\n',
                '    if idx != -1: text = text[:idx].strip()\n',
                '    for token in [\'<|endoftext|>\', \'<|im_end|>\', \'<|im_start|>\']:\n',
                '        text = text.replace(token, \'\')\n',
                '    return text.strip()\n\n',
                'def generate_summary(article_text, use_gtf=True):\n',
                '    prompt = f"Tóm tắt bài báo sau:\\n{article_text}\\n\\nTóm tắt:\\n"\n',
                '    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1500).to(model.device)\n',
                '    input_len = inputs.input_ids.shape[1]\n',
                '    \n',
                '    gen_kwargs = {\n',
                '        "input_ids": inputs.input_ids,\n',
                '        "attention_mask": inputs.attention_mask,\n',
                '        "max_new_tokens": 128,\n',
                '        "num_beams": 4,\n',
                '        "early_stopping": True,\n',
                '        "pad_token_id": tokenizer.eos_token_id\n',
                '    }\n',
                '    \n',
                '    if use_gtf:\n',
                '        # Phải truyền prompt_length vào để tránh phạt những từ có trong bài báo gốc!\n',
                '        gtf_processor = GTFPenaltyLogitsProcessor(vocab_frequencies, prompt_length=input_len, alpha=1.0, base_penalty=0.6)\n',
                '        gen_kwargs["logits_processor"] = LogitsProcessorList([gtf_processor])\n',
                '        \n',
                '    with torch.no_grad(): outputs = model.generate(**gen_kwargs)\n',
                '    summary_ids = outputs[0][input_len:]\n',
                '    raw_summary = tokenizer.decode(summary_ids, skip_special_tokens=True)\n',
                '    return process_qwen(raw_summary)\n\n',
                '# Chạy thử nghiệm trên 1 bài báo mẫu\n',
                'sample_article = """\n',
                'Chiều 15/8, Bộ Y tế ghi nhận thêm 2 ca mắc mới Covid-19, nâng tổng số ca mắc tại Việt Nam lên 930.\n',
                'Ca bệnh 929 (BN929) là bệnh nhân nữ, 57 tuổi, trú tại xã Tiên Thuận, huyện Bến Cầu, tỉnh Tây Ninh.\n',
                'Bệnh nhân từ Mỹ nhập cảnh Sân bay Tân Sơn Nhất ngày 02/8 trên chuyến bay VN2, được cách ly tập trung ngay tại TP. HCM.\n',
                'Sau hai lần xét nghiệm, kết quả dương tính với virus SARS-CoV-2.\n',
                '"""\n\n',
                'print("1. KHÔNG DÙNG GTF-Penalty:")\n',
                'print(generate_summary(sample_article, use_gtf=False))\n',
                'print("-" * 50)\n',
                'print("2. CÓ DÙNG GTF-Penalty:")\n',
                'print(generate_summary(sample_article, use_gtf=True))\n'
            ]
            cell['source'] = new_source

with open('09_Qwen_GTF_Penalty.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
